### ISSUE TITLE
[Q]can i use this device  tree for building rom for samsung device?

### ISSUE THREAD

**Issue by tmvkrpxl0** [eva0034/device_xiaomi_msm8953-common#1]
as i written on the title, i want to use this device tree to build rom for samsung device
ofc same chipset(snadragon 625 msm8953)
should i use this device tree? or find other one with snapdragon 625 based?

**Comment by iscle** [comment]
You might be able to use it as a base, but the kernel a lot of things (like the kernel) will be different. Check if there's another samsung device that already has a custom rom with the same chipset, it's always easier to start with same-brand trees!
